import fs from 'node:fs';
import request from 'supertest';
import { beforeAll, describe, expect, it } from 'vitest';
import { createApp } from '../src/app.js';
import { openDb } from '../src/db.js';
import { seedAdmin } from '../src/seed.js';

/**
 * Update 6 C — row recognition on a synthetic multi-sheet contractor-quotation workbook (generated by
 * `scripts/make-fixture-sinomag.mjs`, run `npm run fixtures:sinomag` to regenerate): breakdown/sub-label rows never
 * become công việc or hạng mục, dimension columns (Dài/Rộng/Cao/Số cấu kiện) are never read as giá, a composite
 * "Tổng cộng"-only price is preserved and applied once, a broken-formula price cell is flagged and not silently 0,
 * and every package/sheet total reconciles with the TONGHOP summary.
 */
const db = openDb(':memory:');
seedAdmin(db, 'admin', 'admin123');
const app = createApp(db, { serveWeb: false });
let token = '';
const A = () => ({ Authorization: `Bearer ${token}` });
const fx = (f: string) => fs.readFileSync(new URL(`./fixtures/${f}`, import.meta.url));
const expected = JSON.parse(fs.readFileSync(new URL('./fixtures/import_sinomag_like.expected.json', import.meta.url), 'utf8'));

beforeAll(async () => {
  const t = (await request(app).post('/api/auth/login').send({ username: 'admin', password: 'admin123' })).body.token;
  token = (await request(app).post('/api/auth/change-password').set({ Authorization: `Bearer ${t}` }).send({ oldPassword: 'admin123', newPassword: 'MatKhau2026!' })).body.token;
});

async function upload() {
  const r = await request(app).post('/api/import/upload').set(A()).attach('file', fx('import_sinomag_like.xlsx'), 'import_sinomag_like.xlsx');
  expect(r.status).toBe(200);
  return r.body.fileId as string;
}
async function newProject(name: string) {
  return (await request(app).post('/api/projects').set(A()).send({ name })).body.id as number;
}

interface PreviewRow {
  type: string;
  stt: string;
  name: string;
  unit: string;
  quantity: number | null;
  unitPrice: number | null;
  amount: number | null;
}
interface BlockDTO {
  sheetName: string;
  total: number;
  fileTotal: number | null;
  ok: boolean | null;
  preview: PreviewRow[];
}

describe('Update 6 C — row recognition (import_sinomag_like.xlsx)', () => {
  it('sub-labels ("DK1", "TRỤC 1,9(8.4+11.6)") never appear as a công việc or a hạng mục; only roman-STT Phần do', async () => {
    const fileId = await upload();
    const pid = await newProject('Sinomag – row recognition');
    const a = (await request(app).post('/api/import/analyze-multi').set(A()).send({ fileId, projectId: pid })).body as { blocks: BlockDTO[] };
    const ct1 = a.blocks.find((b) => b.sheetName === expected.sheet_building_1)!;
    const names = ct1.preview.map((r) => r.name);
    for (const n of expected.ct1.never_items) expect(names, `"${n}" must never appear in the preview`).not.toContain(n);
    const categories = ct1.preview.filter((r) => r.type === 'category').map((r) => r.name);
    expect(categories).toEqual(expected.ct1.fileCategories.map((c: { name: string }) => c.name));
    for (const s of expected.ct1.never_sections) expect(categories, `"${s}" must never become a Phần`).not.toContain(s);
  });

  it('composite price ("Tổng cộng" only, VL/NC blank) is applied once, never split into zero VL+NC', async () => {
    const fileId = await upload();
    const pid = await newProject('Sinomag – composite price');
    const a = (await request(app).post('/api/import/analyze-multi').set(A()).send({ fileId, projectId: pid })).body as { blocks: BlockDTO[] };
    const ct1 = a.blocks.find((b) => b.sheetName === expected.sheet_building_1)!;
    const row = ct1.preview.find((r) => r.name === expected.ct1.composite_item.name)!;
    expect(row.unitPrice).toBe(expected.ct1.composite_item.composite);
    expect(row.amount).toBe(expected.ct1.composite_item.amount);
  });

  it('dimension columns (Dài/Rộng/Cao/Số cấu kiện) are never read as a unit price (no more 44/4/22)', async () => {
    const fileId = await upload();
    const pid = await newProject('Sinomag – dims never priced');
    const a = (await request(app).post('/api/import/analyze-multi').set(A()).send({ fileId, projectId: pid })).body as { blocks: BlockDTO[] };
    const ct1 = a.blocks.find((b) => b.sheetName === expected.sheet_building_1)!;
    const row = ct1.preview.find((r) => r.name === expected.ct1.dims_never_priced.item)!;
    for (const bad of expected.ct1.dims_never_priced.forbiddenPrices) {
      expect(row.unitPrice, `đơn giá của "${row.name}" must not be a dimension value (${bad})`).not.toBe(bad);
    }
  });

  it('every block/sheet total matches the file; TONGHOP reconciles with the project total', async () => {
    const fileId = await upload();
    const pid = await newProject('Sinomag – reconciliation');
    const a = (await request(app).post('/api/import/analyze-multi').set(A()).send({ fileId, projectId: pid })).body as {
      blocks: BlockDTO[];
      summary: { totalCheck: { ok: boolean; file: number } } | null;
      grand: { total: number };
      allOk: boolean;
    };
    expect(a.allOk).toBe(true);
    const totals: Record<string, number> = { [expected.sheet_building_1]: expected.ct1.total, [expected.sheet_building_2]: expected.ct2.total, [expected.sheet_office]: expected.a1.total, [expected.sheet_mep]: expected.dien.total };
    for (const [sheet, total] of Object.entries(totals)) {
      const b = a.blocks.find((x) => x.sheetName === sheet)!;
      expect(b.ok).toBe(true);
      expect(b.total).toBe(total);
      expect(b.fileTotal).toBe(total);
    }
    expect(a.grand.total).toBe(expected.project_total);
    expect(a.summary?.totalCheck?.ok).toBe(true);
    expect(a.summary?.totalCheck?.file).toBe(expected.project_total);
  });

  it('broken-formula price cell (#REF!) is flagged, item is kept, and the error never becomes a silent 0 Thành tiền', async () => {
    const fileId = await upload();
    const pid = await newProject('Sinomag – broken cell');
    const r = (await request(app).post(`/api/projects/${pid}/import-sheets`).set(A()).send({ fileId })).body;
    const items = (await request(app).get(`/api/projects/${pid}/estimate`).set(A())).body.categories.flatMap((c: { items: { name: string }[] }) => c.items);
    const it = items.find((x: { name: string }) => x.name === expected.ct1.broken_cell_item.name);
    expect(it, 'the item with the broken VL cell must still be imported').toBeTruthy();
    expect(it.custom.vl).toBe(expected.ct1.broken_cell_item.appliedVl);
    expect(it.custom.nc).toBe(expected.ct1.broken_cell_item.appliedNc);
    expect(r.created).toBe(10);
  });

  it('each sheet becomes its own hạng mục công trình; item/breakdown counts and quantity_lines text match', async () => {
    const fileId = await upload();
    const pid = await newProject('Sinomag – packages');
    const r = (await request(app).post(`/api/projects/${pid}/import-sheets`).set(A()).send({ fileId })).body;
    expect(r.workPackageIds).toHaveLength(4);

    const packages = (await request(app).get(`/api/projects/${pid}/work-packages`).set(A())).body as { id: number; name: string; sourceSheet: string | null }[];
    const bySheet = (sheet: string) => packages.find((p) => p.sourceSheet === sheet)!;

    const checkPackage = async (sheet: string, expectedItemCount: number, expectedTotal: number) => {
      const wp = bySheet(sheet);
      expect(wp, `no work package for sheet "${sheet}"`).toBeTruthy();
      const scoped = (await request(app).get(`/api/projects/${pid}/work-packages/${wp.id}/estimate`).set(A())).body;
      const items = scoped.categories.flatMap((c: { items: unknown[] }) => c.items);
      expect(items).toHaveLength(expectedItemCount);
      // direct cost (Σ thành tiền) of just this package – NOT costSummary.total, which still adds TT36 chi phí
      // chung/TNCT on top regardless of the package's "bao_gia" mode (that branch is Section 3, not this one).
      expect(scoped.total.total).toBeCloseTo(expectedTotal, 0);
    };
    await checkPackage(expected.sheet_building_1, expected.ct1.itemCount, expected.ct1.total);
    await checkPackage(expected.sheet_building_2, expected.ct2.itemCount, expected.ct2.total);
    await checkPackage(expected.sheet_office, expected.a1.itemCount, expected.a1.total);
    await checkPackage(expected.sheet_mep, expected.dien.itemCount, expected.dien.total);

    // detail/breakdown lines attach to the right item, prefixed with their sub-label text
    const ct1Wp = bySheet(expected.sheet_building_1);
    const scoped = (await request(app).get(`/api/projects/${pid}/work-packages/${ct1Wp.id}/estimate`).set(A())).body;
    const items = scoped.categories.flatMap((c: { items: { id: number; name: string }[] }) => c.items);
    for (const exp of expected.ct1.items as { name: string; details: number }[]) {
      const it = items.find((x: { name: string }) => x.name === exp.name);
      expect(it, `missing item "${exp.name}"`).toBeTruthy();
      const lines = (await request(app).get(`/api/projects/${pid}/items/${it.id}/quantity-lines`).set(A())).body as { description: string }[];
      expect(lines).toHaveLength(exp.details);
    }
    const dk = items.find((x: { name: string }) => x.name === 'Đà kiềng');
    const dkLines = (await request(app).get(`/api/projects/${pid}/items/${dk.id}/quantity-lines`).set(A())).body as { description: string }[];
    expect(dkLines.map((l) => l.description)).toEqual(['DK1: Nhịp 1', 'DK1: Nhịp 2']);
  });

  it('thong ke thep (bảng phụ) and the hidden sheet are never importable / never auto-selected', async () => {
    const fileId = await upload();
    const pid = await newProject('Sinomag – aux + hidden sheets');
    const a = (await request(app).post('/api/import/analyze-multi').set(A()).send({ fileId, projectId: pid })).body;
    const aux = a.sheets.find((s: { name: string }) => s.name === expected.sheet_aux);
    const hidden = a.sheets.find((s: { name: string }) => s.name === expected.sheet_hidden);
    expect(aux.importable).toBe(false);
    expect(hidden.hidden).toBe(true);
    expect(hidden.importable).toBe(false);
    expect(a.selected).not.toContain(aux.index);
    expect(a.selected).not.toContain(hidden.index);
  });
});
