import ExcelJS from 'exceljs';
import {
  amountInWords,
  BUILDING_TYPE_LABELS,
  contingencyInputs,
  defaultTt36Settings,
  evaluateFormula,
  PRICE_SOURCE_LABELS,
  RESOURCE_TYPE_LABELS,
  type Tt36Settings,
} from '@dutoan/core';
import type { LegalDocument } from '@dutoan/core';
import type { Calculation, QuantityLineRow, WorkPackage } from './repo.js';

const FONT = 'Times New Roman';
const MONEY = '#,##0';
const QTY = '#,##0.000';
const THIN: Partial<ExcelJS.Borders> = {
  top: { style: 'thin' },
  left: { style: 'thin' },
  bottom: { style: 'thin' },
  right: { style: 'thin' },
};

type Cell = string | number | null | { formula: string; result?: number };

function setupSheet(ws: ExcelJS.Worksheet, widths: number[], landscape: boolean) {
  ws.columns = widths.map((w) => ({ width: w }));
  ws.pageSetup = {
    paperSize: 9, // A4
    orientation: landscape ? 'landscape' : 'portrait',
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    margins: { left: 0.6, right: 0.4, top: 0.6, bottom: 0.6, header: 0.3, footer: 0.3 },
  };
  ws.headerFooter.oddFooter = '&R Trang &P/&N';
  ws.properties.defaultRowHeight = 18;
}

function title(ws: ExcelJS.Worksheet, row: number, text: string, cols: number, size = 14) {
  ws.mergeCells(row, 1, row, cols);
  const c = ws.getCell(row, 1);
  c.value = text;
  c.font = { name: FONT, size, bold: true };
  c.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
}

function info(ws: ExcelJS.Worksheet, row: number, text: string, cols: number) {
  ws.mergeCells(row, 1, row, cols);
  const c = ws.getCell(row, 1);
  c.value = text;
  c.font = { name: FONT, size: 11, italic: true };
  c.alignment = { horizontal: 'left' };
}

function header(ws: ExcelJS.Worksheet, row: number, labels: string[]) {
  const r = ws.getRow(row);
  labels.forEach((l, i) => {
    const c = r.getCell(i + 1);
    c.value = l;
    c.font = { name: FONT, size: 11, bold: true };
    c.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    c.border = THIN;
    c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE8EEF6' } };
  });
  r.height = 32;
}

/** Write a table row; numFmts maps column index (1-based) → number format. */
function row(ws: ExcelJS.Worksheet, rowNo: number, values: Cell[], opts: { bold?: boolean; numFmts?: Record<number, string>; italic?: boolean } = {}) {
  const r = ws.getRow(rowNo);
  values.forEach((v, i) => {
    const c = r.getCell(i + 1);
    c.value = v as ExcelJS.CellValue;
    c.font = { name: FONT, size: 11, bold: opts.bold, italic: opts.italic };
    c.border = THIN;
    const fmt = opts.numFmts?.[i + 1];
    if (fmt) c.numFmt = fmt;
    c.alignment = { vertical: 'middle', wrapText: typeof v === 'string' && v.length > 20, horizontal: typeof v === 'string' && v.length <= 3 ? 'center' : undefined };
  });
  return r;
}

const sourceLabel = (src: { label: string; notes?: string[] } | undefined) =>
  src ? `${src.label}${src.notes?.length ? ` (${src.notes.join('; ')})` : ''}` : '';

const roman = (n: number) =>
  ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI', 'XVII', 'XVIII', 'XIX', 'XX'][n - 1] ?? String(n);

/** Convert a "diễn giải" formula into an Excel formula when it is valid arithmetic. */
function excelQuantity(formula: string | null | undefined, value: number): Cell {
  if (!formula) return value;
  try {
    evaluateFormula(formula);
  } catch {
    return value;
  }
  const f = formula
    .replace(/\[[^\]]*\]/g, '')
    .replace(/"[^"]*"/g, '')
    .replace(/[×xX]/g, '*')
    .replace(/÷/g, '/')
    .replace(/(\d),(\d)/g, '$1.$2')
    .replace(/\s+/g, '');
  return { formula: f, result: value };
}

/** Unique, ≤31-char worksheet names (Excel's hard limit) for a list of work packages. */
function sheetNames(packages: { name: string }[]): string[] {
  const used = new Set<string>();
  return packages.map((p) => {
    const clean = p.name.replace(/[\\/?*[\]:]/g, ' ').trim() || 'Hạng mục';
    let base = clean.slice(0, 31);
    let name = base;
    for (let n = 2; used.has(name.toLowerCase()); n++) {
      const suffix = ` (${n})`;
      name = base.slice(0, 31 - suffix.length) + suffix;
    }
    used.add(name.toLowerCase());
    return name;
  });
}

/** "Diễn giải khối lượng" of an item: its formula, else its quantity lines (e.g. generated by "Đẩy sang dự toán"). */
export function itemBreakdownText(it: { quantityFormula?: string | null; quantityBreakdown?: string[] | null }): string {
  return it.quantityFormula || (it.quantityBreakdown ?? []).join('\n');
}

/**
 * Split a quantity line for a sheet that lists lines under their item: a take-off line "M1 × 10: 1,8×1,2×0,5 = 10,8"
 * → label "M1 × 10" (column Tên công tác) + breakdown "1,8×1,2×0,5 = 10,8" (column Diễn giải khối lượng); other lines
 * keep their description and expression – a bare numeric expression equal to the result is not repeated.
 */
export function splitLine(line: { description: string; expression: string; result: number | null }): { label: string; breakdown: string } {
  const desc = line.description || '';
  const m = /^(.*? × \d+(?:[.,]\d+)?): (.*=\s*-?[\d.,]+.*)$/.exec(desc);
  if (m) return { label: m[1], breakdown: m[2] };
  const expr = (line.expression ?? '').trim();
  const bare = line.result !== null && /^-?[\d.]+$/.test(expr) && Math.abs(Number(expr) - line.result) < 1e-9;
  return { label: desc, breakdown: bare ? '' : expr };
}

/**
 * Update 6 D: one worksheet per hạng mục công trình (work package) – its own grid exactly as the app applies it
 * (breakdown/diễn giải lines un-numbered and indented under their item, STT continuous inside each Phần), a
 * composite "Đơn giá tổng hợp" column when the file only gave one combined price, Nguồn giá and Ghi chú.
 */
function buildPackageSheet(ws: ExcelJS.Worksheet, wp: WorkPackage, calc: Calculation, linesOf: (itemId: number) => QuantityLineRow[]) {
  setupSheet(ws, [6, 13, 38, 8, 26, 11, 13, 13, 11, 13, 14, 14, 12, 15, 26, 22], true);
  title(ws, 1, wp.nameZh ? `${wp.name.toUpperCase()} / ${wp.nameZh}` : wp.name.toUpperCase(), 16);
  info(ws, 2, wp.note ? `Ghi chú: ${wp.note}` : wp.sourceSheet ? `Nguồn: ${wp.sourceFile ?? ''} / sheet ${wp.sourceSheet}` : '', 16);
  header(ws, 4, ['STT', 'Mã hiệu', 'Tên công tác', 'Đơn vị', 'Diễn giải khối lượng', 'Khối lượng', 'Đơn giá Vật liệu', 'Đơn giá Nhân công', 'Đơn giá Máy', 'Đơn giá tổng hợp', 'Thành tiền Vật liệu', 'Thành tiền Nhân công', 'Thành tiền Máy', 'Thành tiền', 'Nguồn giá', 'Ghi chú']);
  let r = 5;
  const catTotalRows: number[] = [];
  calc.categories.forEach((cat, ci) => {
    const catRow = r++;
    catTotalRows.push(catRow);
    const firstItem = r;
    let stt = 0;
    for (const it of cat.items) {
      stt++;
      const itemRow = r;
      const fp = it.source?.filePrices;
      // Composite price (file gave only "Tổng cộng", no separate VL/NC/M – section C.4): show it ONLY in "Đơn giá
      // tổng hợp", VL/NC/M stay blank (never the internal vl-only split `amountModeCustom` uses for the total), and
      // Thành tiền is computed from it directly once – never shown twice.
      const compositeOnly = fp && fp.vl === null && fp.nc === null && fp.m === null && fp.unit !== null;
      row(
        ws,
        r,
        [
          stt,
          it.normCode,
          it.name,
          it.unit,
          it.quantityFormula ?? '',
          excelQuantity(it.quantityFormula, it.quantity),
          compositeOnly ? null : it.unitCost.vl,
          compositeOnly ? null : it.unitCost.nc,
          compositeOnly ? null : it.unitCost.m,
          compositeOnly ? fp!.unit : null,
          compositeOnly ? null : { formula: `F${r}*G${r}`, result: it.amount.vl },
          compositeOnly ? null : { formula: `F${r}*H${r}`, result: it.amount.nc },
          compositeOnly ? null : { formula: `F${r}*I${r}`, result: it.amount.m },
          compositeOnly ? { formula: `F${r}*J${r}`, result: it.amount.total } : { formula: `SUM(K${r}:M${r})`, result: it.amount.total },
          it.priceSource ?? '',
          it.note ?? '',
        ],
        { numFmts: { 6: QTY, 7: MONEY, 8: MONEY, 9: MONEY, 10: MONEY, 11: MONEY, 12: MONEY, 13: MONEY, 14: MONEY } },
      );
      r++;
      // Breakdown ("diễn giải") lines: un-numbered, indented, their own partial quantity – never counted as a công việc.
      for (const line of linesOf(it.id)) {
        const { label, breakdown } = splitLine(line);
        const rr = row(
          ws,
          r,
          ['', '', `    ${label}`, '', breakdown, line.sign < 0 ? -(line.result ?? 0) : line.result ?? null, '', '', '', '', '', '', '', '', '', ''],
          { italic: true, numFmts: { 6: QTY } },
        );
        rr.getCell(3).font = { name: FONT, size: 10, italic: true, color: { argb: 'FF667085' } };
        r++;
      }
      void itemRow;
    }
    const lastItem = r - 1;
    const sum = (col: string, result: number): Cell => (lastItem >= firstItem ? { formula: `SUM(${col}${firstItem}:${col}${lastItem})`, result } : 0);
    row(
      ws,
      catRow,
      [roman(ci + 1), '', cat.name.toUpperCase(), '', '', '', '', '', '', '', sum('K', cat.total.vl), sum('L', cat.total.nc), sum('M', cat.total.m), sum('N', cat.total.total), '', ''],
      { bold: true, numFmts: { 11: MONEY, 12: MONEY, 13: MONEY, 14: MONEY } },
    );
  });
  const totalRow = r;
  const totalOf = (col: string, result: number): Cell => (catTotalRows.length ? { formula: catTotalRows.map((x) => `${col}${x}`).join('+'), result } : 0);
  row(
    ws,
    totalRow,
    ['', '', 'CỘNG TRƯỚC THUẾ', '', '', '', '', '', '', '', totalOf('K', calc.total.vl), totalOf('L', calc.total.nc), totalOf('M', calc.total.m), totalOf('N', calc.total.total), '', ''],
    { bold: true, numFmts: { 11: MONEY, 12: MONEY, 13: MONEY, 14: MONEY } },
  );
  // The "Nguồn giá" summary (E.2) is NOT appended here: extra rows after CỘNG TRƯỚC THUẾ would be read back as
  // data on round-trip re-import (no explicit range is set). It is aggregated project-wide on "TỔNG HỢP" instead.
  ws.views = [{ state: 'frozen', ySplit: 4 }];
  return totalRow;
}

/** Update 6 E.2: count + value per price_source kind, across every package – "never mixed silently". */
function priceSourceSummaryRows(packages: WorkbookPackageData[]): { label: string; count: number; value: number }[] {
  const byKind = new Map<string, { count: number; value: number }>();
  for (const pkg of packages) {
    for (const cat of pkg.calc.categories) {
      for (const it of cat.items) {
        const kind = pkg.calc.itemPriceSources?.[it.id]?.current ?? null;
        const label = kind ? PRICE_SOURCE_LABELS[kind] ?? kind : 'Chưa xác định';
        const cur = byKind.get(label) ?? { count: 0, value: 0 };
        cur.count++;
        cur.value += it.amount.total;
        byKind.set(label, cur);
      }
    }
  }
  return [...byKind.entries()].map(([label, v]) => ({ label, ...v }));
}

/** "Tổng hợp dự án": per-package totals + project-level lines (chi phí quản lý, VAT…) + grand total, linked to each package sheet. */
function buildTongHopSheet(
  ws: ExcelJS.Worksheet,
  projectName: string,
  packages: { wp: WorkPackage; sheetName: string; totalRow: number; total: number }[],
  summaryLines: { label: string; kind: 'rate' | 'amount'; value: number; amount: number }[],
  priceSourceSummary: { label: string; count: number; value: number }[],
) {
  setupSheet(ws, [6, 40, 12, 14, 20, 30], false);
  title(ws, 1, 'TỔNG HỢP DỰ ÁN', 6);
  info(ws, 2, `Dự án: ${projectName}`, 6);
  header(ws, 4, ['STT', 'Hạng mục công trình', 'Diện tích (m²)', 'Giá trị (đ)', 'Đơn giá / m² (đ)', 'Ghi chú']);
  let r = 5;
  const pkgRows: number[] = [];
  for (const [i, p] of packages.entries()) {
    pkgRows.push(r);
    const area = p.wp.areaM2;
    row(
      ws,
      r,
      [
        i + 1,
        p.wp.name,
        area ?? '',
        { formula: `'${p.sheetName}'!N${p.totalRow}`, result: p.total },
        area ? { formula: `D${r}/C${r}`, result: p.total / area } : '',
        p.wp.note ?? '',
      ],
      { numFmts: { 3: QTY, 4: MONEY, 5: MONEY } },
    );
    r++;
  }
  const packagesTotal = packages.reduce((a, x) => a + x.total, 0);
  const packagesTotalRow = r;
  row(ws, r, ['', 'CỘNG HẠNG MỤC CÔNG TRÌNH', '', { formula: pkgRows.length ? pkgRows.map((x) => `D${x}`).join('+') : '0', result: packagesTotal }, '', ''], {
    bold: true,
    numFmts: { 4: MONEY },
  });
  r++;
  const lineRows: number[] = [];
  for (const l of summaryLines) {
    lineRows.push(r);
    row(ws, r, ['', l.label, l.kind === 'rate' ? `${l.value}%` : '', l.kind === 'rate' ? { formula: `D${packagesTotalRow}*${l.value}/100`, result: l.amount } : l.amount, '', ''], {
      numFmts: { 4: MONEY },
    });
    r++;
  }
  const grandTotal = packagesTotal + summaryLines.reduce((a, l) => a + l.amount, 0);
  row(
    ws,
    r,
    ['', 'TỔNG CỘNG DỰ ÁN', '', { formula: [`D${packagesTotalRow}`, ...lineRows.map((x) => `D${x}`)].join('+'), result: grandTotal }, '', ''],
    { bold: true, numFmts: { 4: MONEY } },
  );
  r += 2;
  if (priceSourceSummary.length) {
    info(ws, r++, 'Tổng hợp theo nguồn giá (price_source):', 6);
    for (const s of priceSourceSummary) {
      row(ws, r, ['', s.label, '', s.value, '', `${s.count} công việc`], { italic: true, numFmts: { 4: MONEY } });
      r++;
    }
  }
}

export interface WorkbookPackageData {
  workPackage: WorkPackage;
  calc: Calculation;
}

export async function buildWorkbook(
  calc: Calculation,
  author: string,
  legalDocs: LegalDocument[],
  packages: WorkbookPackageData[] = [],
  quantityLinesByItem: Map<number, QuantityLineRow[]> = new Map(),
  summaryLines: { label: string; kind: 'rate' | 'amount'; value: number; amount: number }[] = [],
): Promise<ExcelJS.Workbook> {
  const wb = new ExcelJS.Workbook();
  wb.creator = author;
  wb.created = new Date();
  wb.calcProperties.fullCalcOnLoad = true;
  const p = calc.project;
  const projectInfo = [
    `Công trình: ${p.name}`,
    p.ownerName ? `Chủ đầu tư: ${p.ownerName}` : '',
    p.location ? `Địa điểm: ${p.location}` : '',
    `Loại công trình: ${BUILDING_TYPE_LABELS[p.buildingType] ?? p.buildingType}`,
    p.priceBaseDate || p.priceDate ? `Thời điểm lập giá: ${[p.priceBaseDate, p.priceDate].filter(Boolean).join(' – ')}` : '',
  ].filter(Boolean);

  // Update 6 D: "TỔNG HỢP" (first) + one worksheet per hạng mục công trình, exactly as the app applies each package's
  // own grid – before the whole-project TH/DTCT/PTVT/THVT/CLVT/TDT sheets (unchanged, still project-wide for now).
  const names = sheetNames(packages.map((x) => x.workPackage));
  const wsTongHop = wb.addWorksheet('TỔNG HỢP');
  const pkgSheetInfo = packages.map((pkg, i) => {
    const ws = wb.addWorksheet(names[i]);
    const totalRow = buildPackageSheet(ws, pkg.workPackage, pkg.calc, (itemId) => quantityLinesByItem.get(itemId) ?? []);
    return { wp: pkg.workPackage, sheetName: names[i], totalRow, total: pkg.calc.total.total };
  });
  buildTongHopSheet(wsTongHop, p.name, pkgSheetInfo, summaryLines, priceSourceSummaryRows(packages));

  // Sheet creation order = tab order.
  const wsTH = wb.addWorksheet('TH');
  const wsDT = wb.addWorksheet('DTCT');
  const wsPT = wb.addWorksheet('PTVT');
  const wsTV = wb.addWorksheet('THVT');
  const wsCL = wb.addWorksheet('CLVT');
  const wsTDT = wb.addWorksheet('TDT');

  // ------------------------------------------------------------------ THVT
  setupSheet(wsTV, [6, 14, 42, 9, 8, 14, 14, 18, 48], true);
  title(wsTV, 1, 'BẢNG TỔNG HỢP VẬT TƯ', 9);
  info(wsTV, 2, projectInfo[0], 9);
  header(wsTV, 4, ['STT', 'Mã hiệu', 'Tên vật tư, nhân công, máy', 'Đơn vị', 'Loại', 'Khối lượng', 'Giá (đ)', 'Thành tiền (đ)', 'Nguồn giá']);
  const resRow = new Map<string, number>();
  let r = 5;
  calc.resourceSummary.forEach((s, i) => {
    resRow.set(s.code, r);
    row(
      wsTV,
      r,
      [
        i + 1,
        s.code,
        s.name,
        s.unit,
        s.type,
        { formula: `SUMIF(PTVT!$B:$B,B${r},PTVT!$G:$G)`, result: s.quantity },
        s.price,
        { formula: `F${r}*G${r}`, result: s.amount },
        sourceLabel(calc.priceSources[s.code]),
      ],
      { numFmts: { 6: QTY, 7: MONEY, 8: MONEY } },
    ).getCell(9).font = { name: FONT, size: 9, italic: true };
    r++;
  });
  const tvLast = r - 1;
  row(wsTV, r, ['', '', 'TỔNG CỘNG', '', '', '', '', { formula: `SUM(H5:H${Math.max(5, tvLast)})`, result: calc.total.total }, ''], {
    bold: true,
    numFmts: { 8: MONEY },
  });

  // ------------------------------------------------------------------ PTVT
  setupSheet(wsPT, [6, 14, 44, 9, 7, 12, 14, 14, 14, 14, 14, 14], true);
  title(wsPT, 1, 'BẢNG PHÂN TÍCH VẬT TƯ', 12);
  info(wsPT, 2, projectInfo[0], 12);
  header(wsPT, 4, ['STT', 'Mã hiệu', 'Tên công tác / tài nguyên', 'Đơn vị', 'Loại', 'Định mức', 'Khối lượng', 'Đơn giá (đ)', 'Thành tiền / 1 ĐV (đ)', 'ĐG VL', 'ĐG NC', 'ĐG M']);
  const itemHeaderRow = new Map<number, number>();
  const dtItemRow = new Map<number, number>();

  // Pre-compute DTCT row numbers so PTVT can reference quantities.
  let dr = 6; // first data row of DTCT
  for (const cat of calc.categories) {
    dr++; // category subtotal row
    for (const it of cat.items) dtItemRow.set(it.id, dr++);
  }

  r = 5;
  let stt = 0;
  for (const cat of calc.categories) {
    for (const it of cat.items) {
      stt++;
      const hdr = r;
      itemHeaderRow.set(it.id, hdr);
      const first = hdr + 1;
      const last = hdr + it.analysis.length;
      const sumIf = (t: string, result: number): Cell =>
        it.analysis.length ? { formula: `SUMIF(E${first}:E${last},"${t}",I${first}:I${last})`, result } : 0;
      row(
        wsPT,
        hdr,
        [
          stt,
          it.normCode,
          it.name,
          it.unit,
          '',
          '',
          { formula: `DTCT!F${dtItemRow.get(it.id)}`, result: it.quantity },
          '',
          '',
          sumIf('VL', it.unitCost.vl),
          sumIf('NC', it.unitCost.nc),
          sumIf('M', it.unitCost.m),
        ],
        { bold: true, numFmts: { 7: QTY, 10: MONEY, 11: MONEY, 12: MONEY } },
      );
      r++;
      for (const a of it.analysis) {
        const tv = resRow.get(a.resourceCode);
        row(
          wsPT,
          r,
          [
            '',
            a.resourceCode,
            a.name,
            a.unit,
            a.type,
            a.consumption,
            { formula: `F${r}*$G$${hdr}`, result: a.quantity },
            tv ? { formula: `THVT!G${tv}`, result: a.price } : a.price,
            { formula: `F${r}*H${r}`, result: a.unitAmount },
            '',
            '',
            '',
          ],
          { italic: true, numFmts: { 6: '#,##0.0000', 7: QTY, 8: MONEY, 9: MONEY } },
        );
        r++;
      }
    }
  }

  // ------------------------------------------------------------------ DTCT
  setupSheet(wsDT, [6, 13, 42, 8, 20, 12, 13, 13, 13, 15, 15, 15, 16], true);
  title(wsDT, 1, 'BẢNG DỰ TOÁN CHI TIẾT', 13);
  info(wsDT, 2, projectInfo.join('   –   '), 13);
  header(wsDT, 4, ['STT', 'Mã hiệu', 'Tên công tác', 'Đơn vị', 'Diễn giải khối lượng', 'Khối lượng', 'Đơn giá (đ)', '', '', 'Thành tiền (đ)', '', '', 'Tổng cộng (đ)']);
  header(wsDT, 5, ['', '', '', '', '', '', 'Vật liệu', 'Nhân công', 'Máy', 'Vật liệu', 'Nhân công', 'Máy', '']);
  wsDT.mergeCells('G4:I4');
  wsDT.mergeCells('J4:L4');
  for (const col of ['A', 'B', 'C', 'D', 'E', 'F', 'M']) wsDT.mergeCells(`${col}4:${col}5`);
  r = 6; // must match the pre-computed dtItemRow layout above
  const catTotalRows: number[] = [];
  stt = 0;
  calc.categories.forEach((cat, ci) => {
    const catRow = r++;
    catTotalRows.push(catRow);
    const firstItem = r;
    for (const it of cat.items) {
      stt++;
      const hdr = itemHeaderRow.get(it.id)!;
      // Update 6 D fix: an item with no norm analysis (CUSTOM_GTT/MARKET_QUOTE, or an unresolved norm code) has no
      // PTVT breakdown to link to – its own unit cost (already correctly computed either way) must still be WRITTEN,
      // never hard-coded to 0 (problem #4: "Excel export writes 0 for every unit price although the grid shows file prices").
      const ref = (col: string, result: number): Cell => (it.analysis.length ? { formula: `PTVT!${col}${hdr}`, result } : result);
      row(
        wsDT,
        r,
        [
          stt,
          it.normCode,
          it.name,
          it.unit,
          itemBreakdownText(it),
          excelQuantity(it.quantityFormula, it.quantity),
          ref('J', it.unitCost.vl),
          ref('K', it.unitCost.nc),
          ref('L', it.unitCost.m),
          { formula: `F${r}*G${r}`, result: it.amount.vl },
          { formula: `F${r}*H${r}`, result: it.amount.nc },
          { formula: `F${r}*I${r}`, result: it.amount.m },
          { formula: `SUM(J${r}:L${r})`, result: it.amount.total },
        ],
        { numFmts: { 6: QTY, 7: MONEY, 8: MONEY, 9: MONEY, 10: MONEY, 11: MONEY, 12: MONEY, 13: MONEY } },
      );
      if (!it.quantityFormula && it.quantityBreakdown?.length) wsDT.getRow(r).getCell(5).alignment = { wrapText: true, vertical: 'top' };
      r++;
    }
    const lastItem = r - 1;
    const sum = (col: string, result: number): Cell =>
      lastItem >= firstItem ? { formula: `SUM(${col}${firstItem}:${col}${lastItem})`, result } : 0;
    row(
      wsDT,
      catRow,
      [roman(ci + 1), '', cat.name.toUpperCase(), '', '', '', '', '', '', sum('J', cat.total.vl), sum('K', cat.total.nc), sum('L', cat.total.m), sum('M', cat.total.total)],
      { bold: true, numFmts: { 10: MONEY, 11: MONEY, 12: MONEY, 13: MONEY } },
    );
  });
  const dtTotal = r;
  const totalOf = (col: string, result: number): Cell =>
    catTotalRows.length ? { formula: catTotalRows.map((x) => `${col}${x}`).join('+'), result } : 0;
  row(
    wsDT,
    dtTotal,
    ['', '', 'TỔNG CỘNG', '', '', '', '', '', '', totalOf('J', calc.total.vl), totalOf('K', calc.total.nc), totalOf('L', calc.total.m), totalOf('M', calc.total.total)],
    { bold: true, numFmts: { 10: MONEY, 11: MONEY, 12: MONEY, 13: MONEY } },
  );
  wsDT.views = [{ state: 'frozen', ySplit: 5 }];

  // ------------------------------------------------------------------ TH
  // Columns: STT | Khoản mục | Cách tính | Tỷ lệ (%) / hệ số | Giá trị | Ký hiệu | Nguồn / căn cứ
  setupSheet(wsTH, [6, 46, 30, 12, 20, 9, 56], true);
  title(wsTH, 1, 'BẢNG TỔNG HỢP DỰ TOÁN CHI PHÍ XÂY DỰNG', 7);
  info(wsTH, 2, projectInfo.join('   –   '), 7);
  const docs = legalDocs.filter((d) => calc.legalSet.documents.includes(d.id));
  info(wsTH, 3, `Bộ căn cứ pháp lý: ${calc.legalSet.label}${calc.legalSet.status === 'historical' ? ' (lịch sử)' : ''}`, 7);
  wsTH.getCell(3, 1).font = { name: FONT, size: 11, bold: true };
  let r0 = 4;
  for (const d of docs) {
    const dates = [d.issued ? `ban hành ${d.issued}` : '', d.effective ? `hiệu lực ${d.effective}` : ''].filter(Boolean).join(', ');
    info(wsTH, r0++, `– ${d.type} ${d.number}: ${d.title}${dates ? ` (${dates})` : ''}${d.url ? ` – ${d.url}` : ''}${d.verified ? '' : ' [chưa xác minh]'}`, 7);
  }
  if (calc.provisionalRates) {
    info(wsTH, r0, 'CẢNH BÁO: bảng tỷ lệ đang ở trạng thái TẠM (provisional) – chưa đối chiếu với bản PDF đã ký.', 7);
    wsTH.getCell(r0++, 1).font = { name: FONT, size: 11, bold: true, color: { argb: 'FFB42318' } };
  }
  const headRow = r0 + 1;
  header(wsTH, headRow, ['STT', 'Khoản mục chi phí', 'Cách tính', 'Tỷ lệ (%) / hệ số', 'Giá trị (đ)', 'Ký hiệu', 'Nguồn / căn cứ']);
  const lineRow: Record<string, number> = {};
  const cs = calc.costSummary;
  r = headRow + 1;
  cs.lines.forEach((l) => (lineRow[l.code] = r++));
  const dtRef: Record<string, string> = { 'DT.VL': `DTCT!J${dtTotal}`, 'DT.NC': `DTCT!K${dtTotal}`, 'DT.M': `DTCT!L${dtTotal}` };
  const toExcel = (expr: string, rr: number) =>
    expr.replace(/\{([^}]+)\}/g, (_, tok: string) => {
      if (tok === 'rate' || tok === 'coef') return `D${rr}`;
      if (tok.startsWith('rate:')) return `D${lineRow[tok.slice(5)]}`;
      if (dtRef[tok]) return dtRef[tok];
      if (lineRow[tok] === undefined) throw new Error(`Unknown token ${tok}`);
      return `E${lineRow[tok]}`;
    });
  for (const l of cs.lines) {
    const rr = lineRow[l.code];
    const d: Cell = l.coef !== undefined ? l.coef : l.rate ?? '';
    const val: Cell = l.expr ? { formula: toExcel(l.expr, rr), result: l.value } : l.value;
    const rowObj = row(wsTH, rr, [l.stt ?? '', l.name, l.formula, d, val, l.code, l.source ?? ''], {
      bold: l.level === 0,
      numFmts: { 4: l.coef !== undefined ? '0.0000' : '0.00', 5: MONEY },
    });
    rowObj.getCell(7).font = { name: FONT, size: 9, italic: true };
    rowObj.getCell(7).alignment = { wrapText: true, vertical: 'middle' };
  }
  r = lineRow[cs.lines[cs.lines.length - 1].code] + 1;
  const gxdRow = lineRow.GXD ?? lineRow.Gxd;
  const thTotalRow = r;
  row(
    wsTH,
    r,
    [
      '',
      cs.nhaTam ? 'Tổng chi phí xây dựng (GXD + GXDNT)' : 'Tổng chi phí xây dựng',
      '',
      '',
      { formula: cs.nhaTam ? `E${gxdRow}+E${lineRow.GXDNT}` : `E${gxdRow}`, result: cs.total ?? cs.Gxd },
      '',
      '',
    ],
    { bold: true, numFmts: { 5: MONEY } },
  );
  r += 2;
  info(wsTH, r, `Bằng chữ: ${amountInWords(cs.total ?? cs.Gxd)}.`, 7);
  info(wsTH, r + 1, `Nguồn tỷ lệ: ${calc.ratesSource}`, 7);
  [...calc.warnings.map((w) => `Lưu ý: ${w}`), ...calc.notes.map((n) => `Ghi chú: ${n}`)].forEach((w, i) => info(wsTH, r + 2 + i, w, 7));

  // ------------------------------------------------------------------ CLVT
  setupSheet(wsCL, [6, 14, 40, 9, 14, 14, 14, 14, 18], false);
  title(wsCL, 1, 'BẢNG CHÊNH LỆCH GIÁ VẬT TƯ', 9);
  info(wsCL, 2, projectInfo[0], 9);
  header(wsCL, 4, ['STT', 'Mã hiệu', 'Tên vật tư', 'Đơn vị', 'Khối lượng', 'Giá gốc (đ)', 'Giá hiện hành (đ)', 'Chênh lệch (đ)', 'Thành tiền (đ)']);
  r = 5;
  calc.resourceSummary.forEach((s, i) => {
    const tv = resRow.get(s.code)!;
    row(
      wsCL,
      r,
      [
        i + 1,
        s.code,
        `${s.name} (${RESOURCE_TYPE_LABELS[s.type]})`,
        s.unit,
        { formula: `THVT!F${tv}`, result: s.quantity },
        s.basePrice,
        { formula: `THVT!G${tv}`, result: s.price },
        { formula: `G${r}-F${r}`, result: s.price - s.basePrice },
        { formula: `E${r}*H${r}`, result: s.difference },
      ],
      { numFmts: { 5: QTY, 6: MONEY, 7: MONEY, 8: MONEY, 9: MONEY } },
    );
    r++;
  });
  row(
    wsCL,
    r,
    ['', '', 'TỔNG CỘNG', '', '', '', '', '', { formula: `SUM(I5:I${Math.max(5, r - 1)})`, result: calc.resourceSummary.reduce((a, s) => a + s.difference, 0) }],
    { bold: true, numFmts: { 9: MONEY } },
  );

  // ------------------------------------------------------------------ TDT
  setupSheet(wsTDT, [6, 42, 46, 11, 20, 44], true);
  title(wsTDT, 1, 'BẢNG TỔNG HỢP DỰ TOÁN', 6);
  info(wsTDT, 2, projectInfo[0], 6);
  info(wsTDT, 3, `Căn cứ: ${calc.legalSet.label}`, 6);
  header(wsTDT, 4, ['STT', 'Khoản mục chi phí', 'Cách tính', 'Tỷ lệ (%)', 'Giá trị (đ)', 'Nguồn / căn cứ']);
  const s = calc.settings;
  const byCode = Object.fromEntries(calc.totalEstimate.lines.map((l) => [l.code, l]));
  const V = 'SUM(E5:E9)';
  let dp2Formula = `${V}*D11/100`;
  let dp2Rate: string | number = s.contingencyPriceRate ?? 0;
  if (calc.legalSet.id === 'TT36_2026') {
    const ci = contingencyInputs({ ...defaultTt36Settings(), ...s } as Tt36Settings);
    if (ci.mode === 'formula') {
      dp2Rate = '';
      dp2Formula = ci.shares.map((share, i) => `${V}*${share}/100*(${ci.index}^${i + 1}-1)`).join('+');
    }
  }
  const tdtRows: [string, string, string | number, Cell, string][] = [
    [byCode.Gxd.name, byCode.Gxd.formula, '', { formula: `TH!E${thTotalRow}`, result: byCode.Gxd.value }, byCode.Gxd.source ?? ''],
    [byCode.Gtb.name, 'Nhập', '', byCode.Gtb.value, byCode.Gtb.source ?? ''],
    [byCode.Gqlda.name, 'Nhập', '', byCode.Gqlda.value, byCode.Gqlda.source ?? ''],
    [byCode.Gtv.name, 'Nhập', '', byCode.Gtv.value, byCode.Gtv.source ?? ''],
    [byCode.Gk.name, 'Nhập', '', byCode.Gk.value, byCode.Gk.source ?? ''],
    [byCode.Gdp1.name, byCode.Gdp1.formula, s.contingencyQtyRate ?? 0, { formula: `${V}*D10/100`, result: byCode.Gdp1.value }, byCode.Gdp1.source ?? ''],
    [byCode.Gdp2.name, byCode.Gdp2.formula, dp2Rate, { formula: dp2Formula, result: byCode.Gdp2.value }, byCode.Gdp2.source ?? ''],
  ];
  tdtRows.forEach((v, i) => {
    const rr = row(wsTDT, 5 + i, [i + 1, v[0], v[1], v[2], v[3], v[4]], { numFmts: { 4: '0.00', 5: MONEY } });
    rr.getCell(6).font = { name: FONT, size: 9, italic: true };
    rr.getCell(3).alignment = { wrapText: true, vertical: 'middle' };
  });
  row(wsTDT, 12, ['', 'TỔNG DỰ TOÁN', byCode.TDT.formula, '', { formula: 'SUM(E5:E11)', result: calc.totalEstimate.total }, ''], {
    bold: true,
    numFmts: { 5: MONEY },
  });
  info(wsTDT, 14, `Bằng chữ: ${amountInWords(calc.totalEstimate.total)}.`, 6);

  return wb;
}
